const fs = require('fs');
const path = require('path');
const assert = require('assert');

function testTicketsSubtaskEmbeddingContract() {
    const providerPath = path.join(__dirname, '../services/TaskViewerProvider.ts');
    const content = fs.readFileSync(providerPath, 'utf8');

    const sliceBetween = (startNeedle, endNeedle) => {
        const start = content.indexOf(startNeedle);
        assert.notStrictEqual(start, -1, `expected to find ${startNeedle}`);
        const end = content.indexOf(endNeedle, start);
        assert.notStrictEqual(end, -1, `expected to find ${endNeedle} after ${startNeedle}`);
        return content.slice(start, end);
    };

    // 1. Anti-drift: the section header literal has exactly ONE producer. The bare
    // '## Subtasks' heading legitimately appears elsewhere (the feature-file subtask
    // block, and the push-truncation guard), so anchor on the builder-specific literal.
    const headerLiteral = "'\\n\\n## Subtasks\\n<!-- generated by import";
    const headerOccurrences = content.split(headerLiteral).length - 1;
    assert.strictEqual(
        headerOccurrences, 1,
        `the '## Subtasks' header literal must be defined exactly once (found ${headerOccurrences}) — a second one is the drift that caused this defect`
    );
    assert.ok(content.includes('_buildSubtasksSection('), 'TaskViewerProvider must define _buildSubtasksSection');
    assert.ok(content.includes('_buildSubtaskEntry('), 'TaskViewerProvider must define _buildSubtaskEntry as the single per-subtask line producer');

    // 2. importTaskAsDocument delegates to the shared builder rather than inlining it.
    const importTaskBody = sliceBetween('public async importTaskAsDocument(', 'private _buildSubtaskEntry(');
    assert.ok(
        /content \+= this\._buildSubtasksSection\('linear'/.test(importTaskBody),
        "importTaskAsDocument's Linear branch must call _buildSubtasksSection"
    );
    assert.ok(
        /content \+= this\._buildSubtasksSection\('clickup'/.test(importTaskBody),
        "importTaskAsDocument's ClickUp branch must call _buildSubtasksSection"
    );

    // 3. Positive guard for pushTicketEdits truncation. Without this, a future
    // "clean up the duplicate literal" pass deletes the push protection unnoticed.
    assert.ok(
        content.includes("trimmed === '## Subtasks'"),
        'pushTicketEdits must retain the trimmed === ## Subtasks truncation guard'
    );

    // 4. _writeTaskDocument takes subtasks, and importAllTasks groups them by parent.
    assert.ok(content.includes('subtasks: any[] = []'), '_writeTaskDocument must accept an optional subtasks array');
    assert.ok(content.includes('subtasksByParent = new Map'), 'importAllTasks document fast path must build subtasksByParent map');
    assert.ok(
        /subtasksByParent\.get\(String\(item\.id\)\)/.test(content),
        'the subtasksByParent map must be read inside the write loop'
    );

    // 5. THE MERGE RULE — the single most important assertion in this file.
    // A list payload is never authoritative for a parent's complete subtask set, so no
    // branch may emit a section built solely from the payload, and `isDelta` must not
    // appear in the section logic. A "full imports are authoritative, just regenerate"
    // simplification looks like a cleanup in review and silently deletes cross-list subtasks.
    const writeDocBody = sliceBetween('private async _writeTaskDocument(', 'public async importAllTasks(');
    assert.ok(
        /this\._mergeSubtasksSection\(provider, existingSection, subtasks\)/.test(writeDocBody),
        '_writeTaskDocument must build its section via _mergeSubtasksSection'
    );
    assert.strictEqual(
        /_buildSubtasksSection\(/.test(writeDocBody), false,
        '_writeTaskDocument must NOT call _buildSubtasksSection directly — that regenerates the section from the payload and deletes subtasks the payload cannot see'
    );
    assert.strictEqual(
        writeDocBody.includes('isDelta'), false,
        'isDelta must not appear in the section write path — full and delta share one never-delete merge rule'
    );
    const mergeBody = sliceBetween('private _mergeSubtasksSection(', 'private async _writeTaskDocument(');
    assert.ok(
        /const merged = this\._parseSubtaskEntries\(existingSection\)/.test(mergeBody),
        '_mergeSubtasksSection must seed from the existing section before applying the payload'
    );
    assert.strictEqual(
        /\.delete\(/.test(mergeBody), false,
        '_mergeSubtasksSection must never remove an entry because the payload lacks it'
    );

    // 6. Renamed-parent data-loss guard: resolve the prior file by id, not by a
    // title-derived path (the filename is slugified from the CURRENT title).
    assert.ok(
        /const existingFile = await this\._findTicketDocument\(resolvedRoot, provider, id\)/.test(writeDocBody),
        '_writeTaskDocument must resolve the previous file via _findTicketDocument, not a computed path'
    );

    // 7. Non-authoritative fetches must not feed the section at all.
    assert.ok(
        /fetchIsAuthoritative \? \(subtasksByParent\.get/.test(content),
        'subtask writes must be gated on fetchIsAuthoritative — never merge from a knowingly truncated payload'
    );

    // 8. Orphan-subtask upsert only runs into a section that already exists, so
    // "create a section from one delta item" cannot be reintroduced.
    const importAllBody = sliceBetween('const subtasksByParent = new Map', 'let pruned = 0;');
    assert.ok(
        /if \(headingIdx === -1\) \{ continue; \}/.test(importAllBody),
        'the orphan-subtask upsert must skip parents with no existing ## Subtasks section'
    );

    // 9. Rate-limit guard: no per-parent detail fetch inside the document fast path.
    // The ids-based slow path legitimately has one; the fast path runs on a background timer.
    assert.strictEqual(
        /getTaskDetails\(|importTaskAsDocument\(/.test(importAllBody), false,
        'no per-parent detail fetch may appear in importAllTasks document fast path — ~101 requests for a 100-task list would exhaust ClickUp\'s 100 req/min budget on a repeating timer'
    );

    // 10. Stage 3: the conflict guard runs on full imports too, and the prune's lazy
    // re-query is gone (proving the dbTickets hoist landed rather than being bolted alongside).
    assert.strictEqual(
        /if \(isDelta && item\.id\)/.test(content), false,
        'the conflict guard must no longer be delta-only — a full import must not clobber local edits'
    );
    assert.ok(importAllBody.includes('skippedModified++'), 'skippedModified must be reachable on the full-import path');
    assert.ok(
        !content.includes('(dbTickets.length ? dbTickets : await cacheService.getImportedTickets())'),
        'prune loop must use the hoisted dbTickets directly'
    );

    // 11. Embedded descriptions must demote headings, not strip every '#'
    // (a blanket strip mangles hex colours, "C#", and "#123" refs).
    const entryBody = sliceBetween('private _buildSubtaskEntry(', 'private _buildSubtasksSection(');
    assert.strictEqual(
        /replace\(\/#\/g, ''\)/.test(entryBody), false,
        'embedded descriptions must not have every # stripped'
    );
    assert.ok(
        /#\{1,6\}/.test(entryBody),
        'embedded descriptions must demote line-leading headings only'
    );

    console.log('tickets-subtask-embedding.test.js contract test PASSED');
}

if (require.main === module) {
    testTicketsSubtaskEmbeddingContract();
}

module.exports = { testTicketsSubtaskEmbeddingContract };
