const fs = require('fs');
const path = require('path');
const assert = require('assert');

function testTicketsSubtaskEmbeddingContract() {
    const providerPath = path.join(__dirname, '../services/TaskViewerProvider.ts');
    const content = fs.readFileSync(providerPath, 'utf8');

    const sliceBetween = (startNeedle, endNeedle) => {
        const start = content.indexOf(startNeedle);
        assert.notStrictEqual(start, -1, `expected to find ${startNeedle}`);
        const end = content.indexOf(endNeedle, start);
        assert.notStrictEqual(end, -1, `expected to find ${endNeedle} after ${startNeedle}`);
        return content.slice(start, end);
    };

    // Negative assertions on identifiers MUST run against code, not comments. The
    // never-regenerate rule is documented in a comment that names `isDelta` ("Deliberately
    // no `isDelta` fork here"), so a raw substring check goes red against a correct
    // implementation and pressures a coder into deleting the explanation.
    const stripComments = (s) => s
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/^[ \t]*\/\/.*$/gm, '')
        .replace(/([^:])\/\/.*$/gm, '$1');

    // 1. Anti-drift: the section header literal has exactly ONE producer. The bare
    // '## Subtasks' heading legitimately appears elsewhere (the feature-file subtask
    // block, and the push-truncation guard), so anchor on the builder-specific literal.
    const headerLiteral = "'\\n\\n## Subtasks\\n<!-- generated by import";
    const headerOccurrences = content.split(headerLiteral).length - 1;
    assert.strictEqual(
        headerOccurrences, 1,
        `the '## Subtasks' header literal must be defined exactly once (found ${headerOccurrences}) — a second one is the drift that caused this defect`
    );
    assert.ok(content.includes('_buildSubtasksSection('), 'TaskViewerProvider must define _buildSubtasksSection');
    assert.ok(content.includes('_buildSubtaskEntry('), 'TaskViewerProvider must define _buildSubtaskEntry as the single per-subtask line producer');

    // 2. importTaskAsDocument delegates to the shared builder rather than inlining it.
    const importTaskBody = sliceBetween('public async importTaskAsDocument(', 'private _buildSubtaskEntry(');
    assert.ok(
        /content \+= this\._buildSubtasksSection\('linear'/.test(importTaskBody),
        "importTaskAsDocument's Linear branch must call _buildSubtasksSection"
    );
    assert.ok(
        /content \+= this\._buildSubtasksSection\('clickup'/.test(importTaskBody),
        "importTaskAsDocument's ClickUp branch must call _buildSubtasksSection"
    );

    // 3. Positive guard for pushTicketEdits truncation. Without this, a future
    // "clean up the duplicate literal" pass deletes the push protection unnoticed.
    // Keyed on the SHARED helper now — the old `trimmed === '## Subtasks'` literal
    // truncated on a ticket's own heading as readily as on a generated block.
    assert.ok(
        content.includes('stripAppendedBlocksForPush('),
        'pushTicketEdits must truncate via the shared marker-aware helper'
    );
    assert.ok(
        !content.includes("trimmed === '## Subtasks'"),
        'the bare-heading truncation must be gone — it ate ticket-owned ## Subtasks sections'
    );

    // 4. _writeTaskDocument takes subtasks, and importAllTasks groups them by parent.
    assert.ok(content.includes('subtasks: any[] = []'), '_writeTaskDocument must accept an optional subtasks array');
    assert.ok(content.includes('subtasksByParent = new Map'), 'importAllTasks document fast path must build subtasksByParent map');
    assert.ok(
        /subtasksByParent\.get\(String\(item\.id\)\)/.test(content),
        'the subtasksByParent map must be read inside the write loop'
    );

    // 5. THE MERGE RULE — the single most important assertion in this file.
    // A list payload is never authoritative for a parent's complete subtask set, so no
    // branch may emit a section built solely from the payload, and `isDelta` must not
    // appear in the section logic. A "full imports are authoritative, just regenerate"
    // simplification looks like a cleanup in review and silently deletes cross-list subtasks.
    const writeDocBody = sliceBetween('private async _writeTaskDocument(', 'public async importAllTasks(');
    assert.ok(
        /this\._mergeSubtasksSection\(provider, existingSection, subtasks\)/.test(writeDocBody),
        '_writeTaskDocument must build its section via _mergeSubtasksSection'
    );
    assert.strictEqual(
        /_buildSubtasksSection\(/.test(writeDocBody), false,
        '_writeTaskDocument must NOT call _buildSubtasksSection directly — that regenerates the section from the payload and deletes subtasks the payload cannot see'
    );
    assert.strictEqual(
        stripComments(writeDocBody).includes('isDelta'), false,
        'isDelta must not appear in the section write CODE — full and delta share one never-delete merge rule. (A comment may name it; a branch may not.)'
    );
    const mergeBody = sliceBetween('private _mergeSubtasksSection(', 'private async _writeTaskDocument(');
    assert.ok(
        /const merged = this\._parseSubtaskEntries\(existingSection\)/.test(mergeBody),
        '_mergeSubtasksSection must seed from the existing section before applying the payload'
    );
    assert.strictEqual(
        /\.delete\(/.test(mergeBody), false,
        '_mergeSubtasksSection must never remove an entry because the payload lacks it'
    );

    // 6. Renamed-parent data-loss guard: resolve the prior file by id, not by a
    // title-derived path (the filename is slugified from the CURRENT title).
    assert.ok(
        /const existingFile = await this\._findTicketDocument\(resolvedRoot, provider, id\)/.test(writeDocBody),
        '_writeTaskDocument must resolve the previous file via _findTicketDocument, not a computed path'
    );

    // 7. Non-authoritative fetches must not feed the section at all.
    assert.ok(
        /fetchIsAuthoritative \? \(subtasksByParent\.get/.test(content),
        'subtask writes must be gated on fetchIsAuthoritative — never merge from a knowingly truncated payload'
    );

    // 8. Orphan-subtask upsert only runs into a section that already exists, so
    // "create a section from one delta item" cannot be reintroduced.
    const importAllBody = sliceBetween('const subtasksByParent = new Map', 'let pruned = 0;');
    assert.ok(
        /if \(headingIdx === -1\) \{ continue; \}/.test(importAllBody),
        'the orphan-subtask upsert must skip parents with no existing ## Subtasks section'
    );

    // 9. Rate-limit guard: no per-parent detail fetch inside the document fast path.
    // The ids-based slow path legitimately has one; the fast path runs on a background timer.
    assert.strictEqual(
        /getTaskDetails\(|importTaskAsDocument\(/.test(stripComments(importAllBody)), false,
        'no per-parent detail fetch may appear in importAllTasks document fast path — ~101 requests for a 100-task list would exhaust ClickUp\'s 100 req/min budget on a repeating timer'
    );

    // 10. Stage 3: the conflict guard runs on full imports too, and the prune's lazy
    // re-query is gone (proving the dbTickets hoist landed rather than being bolted alongside).
    assert.strictEqual(
        /if \(isDelta && item\.id\)/.test(content), false,
        'the conflict guard must no longer be delta-only — a full import must not clobber local edits'
    );
    assert.ok(importAllBody.includes('skippedModified++'), 'skippedModified must be reachable on the full-import path');
    assert.ok(
        !content.includes('(dbTickets.length ? dbTickets : await cacheService.getImportedTickets())'),
        'prune loop must use the hoisted dbTickets directly'
    );

    // 11. Embedded descriptions must demote headings, not strip every '#'
    // (a blanket strip mangles hex colours, "C#", and "#123" refs).
    const entryBody = sliceBetween('private _buildSubtaskEntry(', 'private _buildSubtasksSection(');
    assert.strictEqual(
        /replace\(\/#\/g, ''\)/.test(entryBody), false,
        'embedded descriptions must not have every # stripped'
    );
    assert.ok(
        /#\{1,6\}/.test(entryBody),
        'embedded descriptions must demote line-leading headings only'
    );

    // 12. The description must be read off the NORMALISED field. Every ClickUp subtask
    // reaching _buildSubtaskEntry has been through _normalizeClickUpTask, which renames
    // the API's `markdown_description` to `markdownDescription`; reading only the raw key
    // makes the whole description embed dead code and leaves a titles-only checklist —
    // "has a ## Subtasks section" while still handing the agent an incomplete spec.
    assert.ok(
        /st\?\.markdownDescription/.test(entryBody),
        '_buildSubtaskEntry must read the normalised markdownDescription field, not only the raw markdown_description key'
    );

    // 13. Legacy-line dedupe. The shipped per-open enrich wrote ClickUp subtasks as
    // `- [ ] ${name}` with NO id, so an id-only merge appends the payload line beside the
    // legacy one — every ClickUp parent ever opened would list its subtasks twice after
    // the next import. The id must be anchored at the END of the line (a title may itself
    // contain parentheses) and a legacy title slot must be written through, not added to.
    assert.ok(content.includes('_parseSubtaskLine('), 'TaskViewerProvider must define _parseSubtaskLine');
    const parseLineBody = sliceBetween('private _parseSubtaskLine(', 'private _parseSubtaskEntries(');
    assert.ok(
        /\\\(\(\[\^\(\)\]\*\)\\\)\$/.test(parseLineBody),
        'the id must be matched at the END of the checklist line, so a title containing parentheses is not mis-keyed'
    );
    assert.ok(
        /merged\.has\(parsed\.titleKey\)/.test(mergeBody),
        '_mergeSubtasksSection must write through a legacy title-keyed slot instead of appending a duplicate line'
    );

    // 14. Every site that pushes ticket body content for DISPLAY must route through the
    // shared strip. Counting them is the ratchet: the 2026-08-06 fix patched one of
    // three and shipped, because nothing pinned how many there were.
    //
    // The `expected` counts are a SNAPSHOT of the current producer set, not an
    // abstract invariant. If you add a new display-content push that strips, BUMP
    // `expected` for that file — do not delete your push to make the number fit,
    // and do not rip out the ratchet. A push that does NOT strip is always a bug.
    //
    // The pushes regex matches only content-bearing pushes (those with `content:` on
    // the same line), NOT error responses (success:false with no content field) —
    // error responses carry no display content and need no strip.
    //
    // TicketsPanelProvider dropped from 2 to 1 on 2026-08-11: the ticketFileChanged and
    // localTicketFileRead producers were merged into ONE `_readTicketFilePayload` helper,
    // so there is one literal strip call left and neither push carries an inline
    // `content:` any more (both spread the helper's payload, which makes `pushes` 0 for
    // that file). Lowering the number alone would gut the ratchet, so the choke point
    // itself is pinned below instead.
    for (const [file, expected] of [['TicketsPanelProvider.ts', 1], ['PlanningPanelProvider.ts', 1]]) {
        const src = fs.readFileSync(path.join(__dirname, '..', 'services', file), 'utf8');
        const pushes = (src.match(/type:\s*'(ticketFileChanged|localTicketFileRead)'.*content:/g) || []).length;
        const strips = (src.match(/stripImportedSubtasksBlock\(/g) || []).length;
        assert.strictEqual(strips, expected, `${file}: every display-content push must strip (bump expected if you added a stripped push)`);
        assert.ok(pushes <= expected, `${file}: a new display push needs a matching strip`);
    }

    // 14b. The consolidated choke point. With both producers sharing one builder, the
    // count above no longer proves each producer strips — these do: the strip lives
    // inside _readTicketFilePayload, and BOTH pushes get their content by spreading that
    // helper's return. A future producer that assembles `content` itself satisfies
    // neither assertion and must route through the helper (or add its own strip and bump
    // `expected` above).
    const provSrc = fs.readFileSync(path.join(__dirname, '..', 'services', 'TicketsPanelProvider.ts'), 'utf8');
    const payloadIdx = provSrc.indexOf('private _readTicketFilePayload(');
    assert.notStrictEqual(payloadIdx, -1, 'TicketsPanelProvider must expose the shared _readTicketFilePayload builder');
    const payloadBody = provSrc.slice(payloadIdx, provSrc.indexOf('\n    private ', payloadIdx + 10));
    assert.ok(
        payloadBody.includes('stripImportedSubtasksBlock('),
        '_readTicketFilePayload is the single display-content choke point — the strip must live inside it'
    );
    assert.ok(
        payloadBody.includes('this._rewriteLocalImagePaths('),
        '_readTicketFilePayload must also rewrite local image paths, or one producer would emit unservable relative asset URLs'
    );
    for (const pushType of ['ticketFileChanged', 'localTicketFileRead']) {
        const re = new RegExp(`type:\\s*'${pushType}'[^}]*\\.\\.\\.payload`);
        assert.match(
            provSrc,
            re,
            `the ${pushType} push must spread _readTicketFilePayload's result, not assemble content itself`
        );
    }

    // 15. Unit assertions on stripImportedSubtasksBlock — the shared display choke point.
    // The function is pure (no imports, no `this`), so we extract and eval it from the
    // TS source to test the ACTUAL implementation, not a copy.
    const displayContentSrc = fs.readFileSync(
        path.join(__dirname, '..', 'services', 'ticketDisplayContent.ts'), 'utf8'
    );
    assert.ok(
        /export function stripImportedSubtasksBlock/.test(displayContentSrc),
        'ticketDisplayContent.ts must export stripImportedSubtasksBlock'
    );
    const fnBodyMatch = displayContentSrc.match(
        /export function stripImportedSubtasksBlock\([^)]*\)[^{]*\{([\s\S]*?)\n\}/
    );
    assert.ok(fnBodyMatch, 'stripImportedSubtasksBlock body must be extractable');
    const stripImportedSubtasksBlock = new Function('content', fnBodyMatch[1]);

    // 15a. Strips heading + marker + body to EOF.
    assert.strictEqual(
        stripImportedSubtasksBlock('Some description\n\n## Subtasks\n<!-- generated by import — content below this line is not pushed to the remote ticket -->\n[ ] Sub 1 (abc) — backlog\n[ ] Sub 2 (def) — backlog'),
        'Some description',
        'stripImportedSubtasksBlock must cut from the heading+marker to EOF'
    );

    // 15b. Leaves a user-authored ## Subtasks heading (no marker) untouched.
    assert.strictEqual(
        stripImportedSubtasksBlock('Some description\n\n## Subtasks\n\n- [ ] My own task\n'),
        'Some description\n\n## Subtasks\n\n- [ ] My own task\n',
        'stripImportedSubtasksBlock must NOT strip a ## Subtasks heading without the generated-by-import marker'
    );

    // 15c. Handles CRLF — assert the stripped OUTPUT, not just that the call didn't throw.
    assert.strictEqual(
        stripImportedSubtasksBlock('Some description\r\n\r\n## Subtasks\r\n<!-- generated by import — content below this line is not pushed to the remote ticket -->\r\n[ ] Sub 1 (abc) — backlog'),
        'Some description',
        'stripImportedSubtasksBlock must handle CRLF between heading and marker'
    );

    // 15d. Returns input unchanged when the block is absent.
    assert.strictEqual(
        stripImportedSubtasksBlock('Just a description with no subtasks block'),
        'Just a description with no subtasks block',
        'stripImportedSubtasksBlock must return input unchanged when no block is present'
    );

    // 16. Unit assertions on stripAppendedBlocksForPush — the shared push choke point.
    //
    // Loaded by TRANSPILING the module, not by regex-extracting the function body. The
    // `[^{]*\{` signature-skip used for stripImportedSubtasksBlock above cannot work
    // here — this function's return type is itself braced
    // (`): { pushBody: string; withheld: boolean } {`), so the skip stops at the RETURN
    // TYPE's brace and the captured "body" is `pushBody: string; …} {`, a SyntaxError
    // inside new Function. Body extraction is also wrong on the merits: the function
    // closes over module-scope declarations (the `g`-flagged APPENDED_HEADING and
    // looksLikeImportedCommentLog), so a lifted body throws ReferenceError and the
    // `lastIndex = 0` re-entrancy reset that cases 16b/16d/16e depend on never runs.
    const ts = require('typescript');
    const displayModule = { exports: {} };
    new Function('exports', 'module', 'require', ts.transpileModule(displayContentSrc, {
        compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 }
    }).outputText)(displayModule.exports, displayModule, require);
    const stripAppendedBlocksForPush = displayModule.exports.stripAppendedBlocksForPush;
    assert.strictEqual(
        typeof stripAppendedBlocksForPush, 'function',
        'ticketDisplayContent.ts must export stripAppendedBlocksForPush'
    );

    let pushResult;

    // 16a. Marker-carrying block is cut.
    pushResult = stripAppendedBlocksForPush('Some description\n\n## Subtasks\n<!-- generated by import — content below this line is not pushed to the remote ticket -->\n- [ ] Sub 1 (abc)\n- [ ] Sub 2 (def)');
    assert.strictEqual(pushResult.pushBody, 'Some description');
    assert.strictEqual(pushResult.withheld, true);

    // 16b. Legacy bare heading + checklist to EOF is cut.
    pushResult = stripAppendedBlocksForPush('# T\n\nintro\n\n## Subtasks\n- [ ] One (a)\n- [ ] Two (b)');
    assert.strictEqual(pushResult.pushBody, '# T\n\nintro');
    assert.strictEqual(pushResult.withheld, true);

    // 16c. Legacy indented `  >` description lines survive even when trailing space stripped.
    pushResult = stripAppendedBlocksForPush('body\n\n## Subtasks\n- [ ] One (a)\n  > note\n  >\n- [ ] Two (b)');
    assert.strictEqual(pushResult.pushBody, 'body');
    assert.strictEqual(pushResult.withheld, true);

    // 16d. Human `## Comments` prose above a legacy `## Subtasks` checklist keeps the prose,
    //      and cuts only the checklist — all-candidate scan, not first-match-wins.
    pushResult = stripAppendedBlocksForPush('# T\n\nintro\n\n## Comments\nThis is real prose.\n\n## Subtasks\n- [ ] One (a)\n- [ ] Two (b)');
    assert.ok(pushResult.pushBody.includes('## Comments'), 'human Comments section must survive');
    assert.ok(!pushResult.pushBody.includes('## Subtasks'), 'legacy Subtasks checklist must be cut');
    assert.strictEqual(pushResult.withheld, true);

    // 16e. The reported bug: a ticket's own `## Subtasks` followed by prose is kept in
    //      full — UNCHANGED, trailing newline included. The kept path returns `body`
    //      verbatim (only the withheld path trimEnd()s), and pushTicketEdits trims for
    //      itself, so asserting a trimmed value here would pin behaviour the function
    //      does not have.
    pushResult = stripAppendedBlocksForPush('# T\n\nintro\n\n## Subtasks\n\nWe will do A, then B.\n');
    assert.strictEqual(pushResult.pushBody, '# T\n\nintro\n\n## Subtasks\n\nWe will do A, then B.\n');
    assert.strictEqual(pushResult.withheld, false);

    // 16f. No heading means unchanged.
    pushResult = stripAppendedBlocksForPush('Just a description');
    assert.strictEqual(pushResult.pushBody, 'Just a description');
    assert.strictEqual(pushResult.withheld, false);

    // 16g. Legacy import-generated `## Comments` log (shipped into ticket docs 2026-06-22,
    //      never marker-carrying) must still be withheld. Comment BODIES are free prose so
    //      the checklist shape test can never match one; without a comments-specific shape
    //      rule the whole imported comment history is pushed into the remote DESCRIPTION.
    pushResult = stripAppendedBlocksForPush(
        '# T\n\nintro\n\n## Comments\n\n**Ada** — 2026-06-22:\n\nLooks good to me.\n\n---\n\n**Grace** — 2026-06-23:\n\nShipping.\n\n---\n'
    );
    assert.strictEqual(pushResult.pushBody, '# T\n\nintro', 'legacy imported comment log must be withheld');
    assert.strictEqual(pushResult.withheld, true);

    // 16h. A human-authored `## Comments` section that opens with prose is NOT an imported
    //      log and must push in full — the discriminator is the bold-author FIRST line.
    pushResult = stripAppendedBlocksForPush('# T\n\nintro\n\n## Comments\n\nRemember to check the **staging** build before release.\n');
    assert.ok(pushResult.pushBody.includes('## Comments'), 'human Comments prose must survive');
    assert.strictEqual(pushResult.withheld, false);

    // 17. The importTicketSubtasks verb handler must restamp last_synced_at after a
    // successful enrichment. Without this, an explicit verb caller (HTTP / standalone)
    // poisons the refresh path — the file reads as falsely "modified" and is permanently
    // excluded from importAllTasks (skippedModified). The restamp uses the same
    // registerImportedTicket pattern as TaskViewerProvider's orphan-upsert path.
    const ticketsProviderSrc = fs.readFileSync(
        path.join(__dirname, '..', 'services', 'TicketsPanelProvider.ts'), 'utf8'
    );
    const handlerBody = ticketsProviderSrc.slice(
        ticketsProviderSrc.indexOf("case 'importTicketSubtasks':"),
        ticketsProviderSrc.indexOf("case 'fetchMoveTargets':")
    );
    assert.ok(
        /registerImportedTicket/.test(handlerBody),
        'importTicketSubtasks handler must call registerImportedTicket to restamp last_synced_at after enrichment'
    );

    // ── 18. Attachment provenance sidecar (`_attachments.json`). ─────────────────
    // "Is this downloaded?" must be answered from what was RECORDED for this ticket, not
    // guessed from a filename in a folder shared by every ticket in the list. A bare
    // existsSync(join(targetDir, filename)) as the only isDownloaded source is the original
    // defect: two tickets with an identically-named attachment claimed each other's file.
    const getListBody = sliceBetween('public async getAttachmentList(', 'public static readonly SOURCE_PRESETS');
    assert.ok(
        /_readAttachmentIndex\(/.test(getListBody),
        'getAttachmentList must resolve isDownloaded from the recorded attachment index'
    );
    assert.ok(
        /hasProvenance/.test(getListBody),
        'getAttachmentList must keep the no-provenance legacy fallback scoped by a hasProvenance gate'
    );
    assert.ok(
        /_ticketAttachmentsDir\(/.test(getListBody),
        'getAttachmentList must resolve the per-TICKET directory, not the picker hierarchy'
    );

    // The sidecar key must be the provider's STABLE attachment id. Both providers re-sign
    // attachment URLs per fetch, so a raw-URL key misses on the very next list fetch and
    // the download is silently "forgotten" — the exact symptom this sidecar removes.
    const downloadBody = sliceBetween('public async downloadAttachment(', 'public async getAttachmentList(');
    assert.ok(
        /_recordAttachment\([^)]*_assetKey\(/.test(stripComments(downloadBody).replace(/\s+/g, ' ')),
        'downloadAttachment must record provenance keyed by _assetKey(...), never a raw url'
    );

    // Layer 2 (PRD contract #7): without these registrations the browser cockpit's
    // attachments modal returns success: true with no rows and prints "No attachments
    // found" for every ticket — a faked success (contract #6).
    const bootstrapSrc = fs.readFileSync(
        path.join(__dirname, '..', 'standalone', 'bootstrap.ts'), 'utf8'
    );
    for (const cmd of ['switchboard.getAttachmentList', 'switchboard.downloadAttachment']) {
        assert.ok(
            bootstrapSrc.includes(`switchboardCommandRegistry.register('${cmd}'`),
            `standalone bootstrap must register ${cmd} — otherwise the cockpit modal fakes success`
        );
    }

    // ── 19. Inline-image relocalisation on import. ───────────────────────────────
    // `replacements` (local src -> hosted URL) having zero consumers WAS the defect, so
    // pin that it is both produced and consumed.
    const imageHelperSrc = fs.readFileSync(
        path.join(__dirname, '..', 'services', 'ImageHostingHelper.ts'), 'utf8'
    );
    assert.ok(
        /export async function hostInlineImages[\s\S]{0,600}?replacements/.test(imageHelperSrc),
        'hostInlineImages must return replacements — dropping it is what broke refetch'
    );
    const pushBody2 = sliceBetween('public async pushTicketEdits(', 'private async _removeOrphanTicketFiles');
    assert.ok(
        /res\.replacements/.test(pushBody2),
        'pushTicketEdits must consume hostInlineImages().replacements'
    );
    assert.ok(
        /alreadyHosted/.test(pushBody2),
        'pushTicketEdits must pass an alreadyHosted lookup — without it every push after a '
        + 'refetch re-uploads the same image and the remote accumulates a duplicate attachment'
    );

    // BOTH import write sites, not one. The reported symptom appears on refetch (the bulk
    // path), so fixing only importTaskAsDocument leaves the reported bug alive.
    for (const [fnStart, fnEnd] of [
        ['public async importTaskAsDocument(', 'private async _ticketAttachmentsDir'],
        ['private async _writeTaskDocument(', 'private static readonly _DELETION_PROBE_CAP'],
    ]) {
        const body = sliceBetween(fnStart, fnEnd);
        const relocalIdx = body.indexOf('_relocalizeInlineImages(');
        const writeIdx = body.indexOf('fs.writeFileSync(filePath');
        assert.ok(relocalIdx !== -1, `${fnStart} must call _relocalizeInlineImages`);
        assert.ok(writeIdx !== -1, `${fnStart} must write the document with writeFileSync`);
        assert.ok(
            relocalIdx < writeIdx,
            `${fnStart} must relocalise BEFORE writeFileSync — after it, the file on disk still holds CDN URLs`
        );
    }

    // ── 20. _assetKey / _relocalizeInlineImages behaviour. ───────────────────────
    // Transpile the provider's two pure helpers out of the class and exercise them. The
    // re-signed-URL case is the one that decides whether the fix works at all: keyed on
    // the raw URL, relocalisation silently no-ops in production while every other test
    // stays green.
    const assetKeyBody = content.slice(
        content.indexOf('\n', content.indexOf('private _assetKey(')) + 1,
        content.indexOf('\n    }', content.indexOf('private _assetKey('))
    );
    const _assetKey = new Function('attachmentId', 'url', assetKeyBody);
    assert.strictEqual(_assetKey('abc123', 'https://x/y.png?sig=1'), 'abc123', 'a present attachment id wins');
    assert.strictEqual(
        _assetKey(undefined, 'https://attachments-public.clickup.com/a/x.png?X-Amz-Signature=AAA&X-Amz-Expires=3600'),
        _assetKey(undefined, 'https://attachments-public.clickup.com/a/x.png?X-Amz-Signature=BBB&X-Amz-Expires=3600'),
        'two re-signings of one asset must produce the SAME key — this is the 60-minute-TTL regression guard'
    );
    assert.strictEqual(
        _assetKey(undefined, 'https://attachments-public.clickup.com/a/x.png?X-Amz-Signature=AAA'),
        'https://attachments-public.clickup.com/a/x.png',
        'the fallback key is origin+pathname with the signature query dropped'
    );
    assert.strictEqual(_assetKey(undefined, 'not a url'), 'not a url', 'an unparseable url is its own key');

    const relocalBody = content.slice(
        content.indexOf('\n', content.indexOf('private _relocalizeInlineImages(')) + 1,
        content.indexOf('\n    }', content.indexOf('private _relocalizeInlineImages('))
    );
    const relocalFn = new Function('fs', 'path', 'content', 'dir', 'key', 'targetFilePath', relocalBody);
    const ticketDir = '/tmp/tickets/clickup/list';
    const shot = path.join(ticketDir, 'attachments', 'shot.png');
    const makeSelf = (index, existing) => ({
        _readAttachmentIndex: () => index,
        _assetKey: (id, url) => _assetKey(id, url),
        __existing: existing,
    });
    const outside = '/tmp/elsewhere/outside.png';
    const fakeFs = { existsSync: (p) => p === shot || p === outside };
    const call = (body, index) => relocalFn.call(
        makeSelf(index), fakeFs, path, body, path.join(ticketDir, 'attachments'), 'clickup_t1',
        path.join(ticketDir, 'clickup_t1_a-ticket.md')
    );
    const hostedA = 'https://attachments-public.clickup.com/a/shot.png?X-Amz-Signature=AAA';
    const hostedB = 'https://attachments-public.clickup.com/a/shot.png?X-Amz-Signature=BBB';
    // A CDN URL whose BASENAME is not on disk anywhere. The sidecar is a cache, not a
    // gate: when it answers with nothing (or with a path that is gone) the function
    // probes the filesystem for the URL's last path segment before giving up. So a
    // "must keep the CDN URL" case has to use a basename the probe cannot find —
    // otherwise it asserts the absence of a fallback that deliberately exists, and the
    // fixture, not the code, is what fails.
    const hostedMissing = 'https://attachments-public.clickup.com/a/absent.png?X-Amz-Signature=AAA';
    const missingKey = 'https://attachments-public.clickup.com/a/absent.png';
    const idx = { clickup_t1: { 'https://attachments-public.clickup.com/a/shot.png': shot } };

    assert.strictEqual(
        call(`before ![shot](${hostedA}) after`, idx),
        'before ![shot](attachments/shot.png) after',
        'a mapped hosted URL must relocalise to a ticket-relative path'
    );
    assert.strictEqual(
        call(`![shot](${hostedB})`, idx),
        '![shot](attachments/shot.png)',
        'a RE-SIGNED url for the same asset must still relocalise — keyed on the raw url it would not'
    );
    assert.strictEqual(
        call(`![a](${hostedA}) and ![b](${hostedB})`, idx),
        '![a](attachments/shot.png) and ![b](attachments/shot.png)',
        'every occurrence of a mapped asset must rewrite, not just the first'
    );
    assert.strictEqual(
        call('![other](https://example.com/nope.png)', idx),
        '![other](https://example.com/nope.png)',
        'an unmapped url must be untouched'
    );
    assert.strictEqual(
        call('![d](data:image/png;base64,AAAA)', idx),
        '![d](data:image/png;base64,AAAA)',
        'a data: uri must be untouched'
    );
    assert.strictEqual(
        call(`![gone](${hostedMissing})`, { clickup_t1: { [missingKey]: '/tmp/deleted.png' } }),
        `![gone](${hostedMissing})`,
        'a recorded file that no longer exists, with no local copy to probe, must keep the CDN URL rather than emit a broken path'
    );
    // The other half of the same rule: the record is stale but the asset IS on disk
    // under its CDN basename, so disk truth outranks the sidecar and it relocalises.
    // (Observed on clickup_86d3y200v — five inline images present in the ticket
    // directory, all emitted as CDN URLs because the sidecar had no row.)
    assert.strictEqual(
        call(`![found](${hostedA})`, { clickup_t1: { 'https://attachments-public.clickup.com/a/shot.png': '/tmp/deleted.png' } }),
        '![found](attachments/shot.png)',
        'a stale record whose asset is on disk under the CDN basename must relocalise from disk'
    );
    assert.strictEqual(
        call(`![out](https://attachments-public.clickup.com/a/outside.png?X-Amz-Signature=AAA)`,
            { clickup_t1: { 'https://attachments-public.clickup.com/a/outside.png': outside } }),
        '![out](https://attachments-public.clickup.com/a/outside.png?X-Amz-Signature=AAA)',
        'a source outside the ticket directory must keep the CDN URL rather than emit ../..'
    );
    assert.strictEqual(
        call(`![none](${hostedMissing})`, {}),
        `![none](${hostedMissing})`,
        'no sidecar record at all must be a clean no-op (the normal state on legacy installs)'
    );
    // Inline-image uploads live in the `#images` namespace so getAttachmentList's
    // download-provenance fallback is not disarmed by them — but relocalisation must read
    // BOTH namespaces, or the push-recorded mapping is invisible to import.
    assert.strictEqual(
        call(`![shot](${hostedA})`, { 'clickup_t1#images': { 'https://attachments-public.clickup.com/a/shot.png': shot } }),
        '![shot](attachments/shot.png)',
        'relocalisation must read the #images namespace, not just the download namespace'
    );
    // The download namespace must remain readable on its own (an attachment we pulled down
    // and that the description also references inline).
    assert.strictEqual(
        call(`![shot](${hostedA})`, idx),
        '![shot](attachments/shot.png)',
        'relocalisation must still read the download namespace'
    );

    // getAttachmentList's legacy fallback must key on the DOWNLOAD namespace only. Reading
    // the merged set meant one push of a locally-authored inline image set hasProvenance and
    // every pre-change download on the install base lost its Open/Reveal buttons.
    assert.ok(
        /_readAttachmentIndex\(targetDir\)\[key\]/.test(getListBody),
        'getAttachmentList must read the ticket download namespace only when deciding hasProvenance'
    );
    assert.strictEqual(
        /#images/.test(getListBody), false,
        'getAttachmentList must NOT fold the inline-image upload namespace into its provenance gate'
    );

    // ── 21. _resolveRecordedAsset: the inline-lookup fallback chain, EXECUTED. ──────
    // §20's fake `self` supplies neither _resolveRecordedAsset nor _recordAttachment, so
    // every fallback and the write-back are skipped there by the `typeof … === 'function'`
    // guards — green by absence. These run the real bodies.
    const tsc = require('typescript');
    const transpileMethods = (names) => {
        const bodies = names.map(n => {
            const start = content.indexOf(`private ${n}(`);
            assert.notStrictEqual(start, -1, `expected to find ${n}`);
            return content.slice(start, content.indexOf('\n    }', start) + 6).replace(/^\s*private\s+/, '');
        }).join('\n');
        const src = `class Probe {\n    constructor(fs, path) { this.fs = fs; this.path = path; }\n${bodies}\n}\nmodule.exports = Probe;`;
        const js = tsc.transpileModule(src, { compilerOptions: { target: tsc.ScriptTarget.ES2020 } }).outputText;
        const mod = { exports: {} };
        new Function('exports', 'module', 'fs', 'path', js)(mod.exports, mod, fsShim, path);
        return mod.exports;
    };
    // The two methods reference the module-scope `fs`/`path`; inject them as free variables.
    let fsShim = { existsSync: () => false };
    const Probe = transpileMethods(['_normalizeAssetName', '_resolveRecordedAsset']);
    const probe = new Probe();
    const attDir = '/tmp/tickets/clickup/list/attachments';

    // 21a. Id-from-URL, against the real shape on the install (plan test 3).
    assert.strictEqual(
        probe._resolveRecordedAsset(
            { '72aa032b-015f-4a2e-b1a8-d26799aa3f31.png': `${attDir}/image-1786413138003.png` },
            'https://t6909707.p.clickup-attachments.com/t6909707/72aa032b-015f-4a2e-b1a8-d26799aa3f31/image.png',
            attDir
        ),
        `${attDir}/image-1786413138003.png`,
        'the id segment + the last segment\'s extension must resolve an id-keyed record exactly'
    );

    // 21b. Id-from-URL with an extension-less last segment (plan test 4).
    assert.strictEqual(
        probe._resolveRecordedAsset(
            { 'aaaa1111-2222-3333-4444-555566667777': `${attDir}/wireframe.png` },
            'https://t6909707.p.clickup-attachments.com/t6909707/aaaa1111-2222-3333-4444-555566667777/record%20screen%20wireframe',
            attDir
        ),
        `${attDir}/wireframe.png`,
        'a ref with no extension on its last segment must fall back to the bare id segment'
    );

    // 21c. Mojibake-encoded narrow no-break space (plan test 5). BOTH encodings must
    // resolve — a naive decodeURIComponent comparison passes the second and silently
    // fails the first, which is the exact miss this fallback exists to close.
    const nnbsp = `${attDir}/Screenshot 2026-07-16 at 11.55.42 am.png`;
    for (const [label, enc] of [['latin-1 mojibake', '%C3%A2%C2%80%C2%AF'], ['correct utf-8', '%E2%80%AF']]) {
        assert.strictEqual(
            probe._resolveRecordedAsset(
                { 'some-id.png': nnbsp },
                `https://t6909707.p.clickup-attachments.com/t/x/Screenshot%202026-07-16%20at%2011.55.42${enc}am.png`,
                attDir
            ),
            nnbsp,
            `basename fallback must survive the ${label} form of U+202F`
        );
    }

    // 21d. Ambiguity refused (plan test 6). Getting the WRONG screenshot inline is worse
    // than keeping the CDN URL, so two candidates must resolve to none.
    assert.strictEqual(
        probe._resolveRecordedAsset(
            { 'a.png': `${attDir}/image.png`, 'b.png': `${attDir}/sub/image.png` },
            'https://t6909707.p.clickup-attachments.com/t/unknown-id/image.png',
            attDir
        ),
        undefined,
        'two index values sharing a basename must refuse to resolve rather than guess'
    );

    // 21e. Flat-path probe, and traversal refusal (plan test 7).
    fsShim = { existsSync: (p) => p === path.join(attDir, 'shot.png') };
    const Probe2 = transpileMethods(['_normalizeAssetName', '_resolveRecordedAsset']);
    const probe2 = new Probe2();
    assert.strictEqual(
        probe2._resolveRecordedAsset({}, 'https://t6909707.p.clickup-attachments.com/t/x/shot.png', attDir),
        path.join(attDir, 'shot.png'),
        'an empty index must still adopt a file sitting at <dir>/<basename>'
    );
    let probed = [];
    fsShim = { existsSync: (p) => { probed.push(p); return false; } };
    const Probe3 = transpileMethods(['_normalizeAssetName', '_resolveRecordedAsset']);
    new Probe3()._resolveRecordedAsset({}, 'https://t6909707.p.clickup-attachments.com/t/x/..%2F..%2F.ssh%2Fid_rsa', attDir);
    for (const p of probed) {
        assert.ok(
            path.resolve(p).startsWith(path.resolve(attDir) + path.sep),
            `the flat-path probe must never stat outside the attachments dir (probed ${p})`
        );
    }

    // 21f. A malformed ref must fall through every branch without throwing (plan test 11).
    assert.doesNotThrow(
        () => new Probe3()._resolveRecordedAsset({ 'x.png': `${attDir}/x.png` },
            'truncated — open the ticket for the full description', attDir),
        'a non-URL ref must not throw out of the resolver'
    );

    // ── 22. Auto-download on import: the seams that decide whether it is safe. ──────
    const hydrateBody = sliceBetween('private async _hydrateTicketAssets(', 'public async downloadAttachment(');
    const fetchBody = sliceBetween('private async _fetchAssetToDisk(', 'private async _hydrateTicketAssets(');
    const streamBody = sliceBetween('private async _streamHttpsToFile(', 'private async _fetchAssetToDisk(');

    // 22a. Ordering at BOTH write sites: hydrate -> relocalise -> write. Hydrating after
    // relocalisation downloads bytes the rewrite has already declined to use.
    for (const [fnStart, fnEnd] of [
        ['public async importTaskAsDocument(', 'private async _ticketAttachmentsDir'],
        ['private async _writeTaskDocument(', 'private static readonly _DELETION_PROBE_CAP'],
    ]) {
        const body = sliceBetween(fnStart, fnEnd);
        const hydrateIdx = body.indexOf('_hydrateTicketAssets(');
        const relocalIdx = body.indexOf('_relocalizeInlineImages(');
        assert.ok(hydrateIdx !== -1, `${fnStart} must hydrate assets — the bulk path is how the 69 unresolved refs arrived`);
        assert.ok(hydrateIdx < relocalIdx, `${fnStart} must hydrate BEFORE relocalising, or the first import always misses`);
    }

    // 22b. The Linear token goes to uploads.linear.app and NOWHERE else, matched on the
    // PARSED hostname. A substring test (`url.includes('.linear.app')`) hands the token to
    // `https://evil.example/.linear.app/x.png` — reachable by anyone who can type into a
    // ticket description once fetching is automatic.
    assert.ok(
        /hostname[\s\S]{0,160}[!=]==\s*'uploads\.linear\.app'/.test(fetchBody),
        'the Linear auth test must compare a parsed hostname for equality with uploads.linear.app'
    );
    assert.strictEqual(
        /includes\(\s*'\.?linear[-.]/.test(fetchBody), false,
        'the Linear auth test must NOT be a substring match on the raw URL'
    );

    // 22c. The Authorization header must be dropped on a cross-origin redirect. This is a
    // CORRECTNESS test, not only a security one: uploads.linear.app 302s to a pre-signed
    // GCS URL, and GCS answers 400/403 to a request carrying a foreign auth header — so a
    // "pass the headers through too" cleanup breaks every Linear image.
    assert.ok(
        /sameOrigin\s*\?\s*options\s*:\s*\{\}/.test(streamBody),
        'redirect options must be dropped wholesale on a cross-origin hop, keeping only same-origin headers'
    );

    // 22d. Automatic fetches of description URLs are allowlisted. Descriptions are
    // user-authored markdown; without this an author can point the importer at any host.
    for (const host of ['clickup-attachments.com', 'uploads.linear.app']) {
        assert.ok(hydrateBody.includes(host), `the description-sweep allowlist must include ${host}`);
    }
    assert.ok(
        hydrateBody.indexOf('hostOk(') !== -1 && hydrateBody.indexOf('hostOk(') < hydrateBody.lastIndexOf('_fetchAssetToDisk('),
        'the allowlist must gate the description sweep BEFORE the fetch, not after'
    );

    // 22e. No HEAD pre-flight: uploads.linear.app answers HEAD chunked with no
    // content-length, so a pre-flight size check is an extra request AND unreliable.
    assert.strictEqual(
        /method:\s*'HEAD'/.test(streamBody + fetchBody), false,
        'asset fetching must never issue a HEAD pre-flight — stream-and-count is the portable guard'
    );
    assert.ok(/received\s*>\s*maxBytes/.test(streamBody), 'the size cap must be enforced by a streaming byte counter');

    // 22f. The kill switch, and the caps. A silent cap reads as "covered everything".
    assert.ok(
        /ticketsDownloadInlineImages\s*!==\s*false/.test(hydrateBody),
        'an absent ticketsDownloadInlineImages key must mean ON — this ships default-ON by explicit PRD override'
    );
    for (const cap of ['_MAX_ASSETS_PER_TICKET', '_MAX_ASSET_BYTES', '_MAX_RUN_ASSET_FILES', '_MAX_RUN_ASSET_BYTES', '_ASSET_TIMEOUT_MS', '_ASSET_REDIRECT_HOPS']) {
        assert.ok(content.includes(`readonly ${cap} =`), `${cap} must be a declared bound, not an inline literal`);
    }

    // 22g. Idempotence probe and inline rewrite must share ONE resolver. A hand-rolled
    // probe that only checks the url key misses every id-keyed record on the install base
    // and turns each background sync into a re-download-and-duplicate loop.
    assert.ok(
        hydrateBody.includes('this._resolveRecordedAsset('),
        'the "already have this?" probe must call the same resolver the inline rewrite uses'
    );
    // Collision suffixes must be STABLE, never Date.now(): a timestamp suffix is what put
    // seven copies of one screenshot in a single attachments directory.
    assert.strictEqual(
        /uniqueFilename[\s\S]{0,400}?Date\.now\(\)/.test(hydrateBody), false,
        'the download collision suffix must be a stable digest, not a timestamp'
    );

    // 22h. The run budget must be opened and closed on EVERY importAllTasks exit. Leaking a
    // spent budget onto the field makes the next single-ticket import silently download
    // nothing, with no log line to explain it.
    const runBudgetBody = sliceBetween('public async importAllTasks(', 'public async deleteTicket(');
    const opens = (runBudgetBody.match(/_importRunBudget = \{/g) || []).length;
    const closes = (runBudgetBody.match(/_importRunBudget = null/g) || []).length;
    assert.strictEqual(opens, 1, 'the run budget must be opened exactly once, before the fast/slow path branch');
    assert.strictEqual(closes, 2, 'both importAllTasks exits (fast path and slow path) must close the run budget');
    assert.ok(
        runBudgetBody.indexOf('_importRunBudget = {') < runBudgetBody.indexOf('for (const item of items)'),
        'the run budget must be opened before the document fast path, or the slow path inherits a stale one'
    );

    console.log('tickets-subtask-embedding.test.js contract test PASSED');
}

if (require.main === module) {
    testTicketsSubtaskEmbeddingContract();
}

module.exports = { testTicketsSubtaskEmbeddingContract };
