const fs = require('fs');
const path = require('path');
const assert = require('assert');

function testTicketsSubtaskEmbeddingContract() {
    const providerPath = path.join(__dirname, '../services/TaskViewerProvider.ts');
    const content = fs.readFileSync(providerPath, 'utf8');

    // 1. Anchor check for exact literal occurrence of '\n\n## Subtasks\n'
    const literalMatches = content.match(/\n\n## Subtasks\\n/g) || [];
    assert.strictEqual(literalMatches.length, 0, 'No double escaped string literals');
    
    // Check _buildSubtasksSection exists and contains '\n\n## Subtasks\n'
    assert.ok(content.includes('_buildSubtasksSection('), 'TaskViewerProvider must define _buildSubtasksSection');
    assert.ok(content.includes("## Subtasks\n<!-- generated by import"), 'Must contain subtasks section header with marker');

    // 2. Neither importTaskAsDocument nor _writeTaskDocument inline builds Subtasks heading directly
    const importTaskMatch = content.match(/importTaskAsDocument[\s\S]*?_buildSubtasksSection/);
    assert.ok(importTaskMatch, 'importTaskAsDocument must call _buildSubtasksSection');

    // 3. Positive guard for pushTicketEdits truncation logic
    assert.ok(content.includes("trimmed === '## Subtasks'"), 'pushTicketEdits must retain trimmed === ## Subtasks truncation guard');

    // 4. _writeTaskDocument signature & subtasksByParent map in importAllTasks
    assert.ok(content.includes('subtasks: any[] = []'), '_writeTaskDocument must accept optional subtasks array');
    assert.ok(content.includes('subtasksByParent = new Map'), 'importAllTasks document fast path must build subtasksByParent map');

    // 5. _findTicketDocument used for data loss guard
    assert.ok(content.includes('_findTicketDocument('), '_writeTaskDocument / helper must resolve ticket via _findTicketDocument');

    // 6. Prune no longer contains fallback query
    assert.ok(!content.includes('(dbTickets.length ? dbTickets : await cacheService.getImportedTickets())'), 'prune loop must use hoisted dbTickets directly');

    console.log('tickets-subtask-embedding.test.js contract test PASSED');
}

if (require.main === module) {
    testTicketsSubtaskEmbeddingContract();
}

module.exports = { testTicketsSubtaskEmbeddingContract };
