/**
 * The `## Subtasks` block that importTicketSubtasks appends is context for agents
 * reading the local .md — never for the detail pane, which renders its own live
 * Subtasks nav above the description. Cut from the heading carrying the
 * generated-by-import marker to EOF.
 *
 * Keyed on heading + marker, never the heading alone: a ticket whose own
 * description contains "## Subtasks" must render in full.
 *
 * DISPLAY ONLY. `rawContent` (edit + push) must keep the block — pushTicketEdits
 * truncates at the heading so it never reaches the remote, and a save built from
 * stripped content would erase it from the file.
 */
export function stripImportedSubtasksBlock(content: string): string {
    const idx = content.search(/^##[ \t]+Subtasks[ \t]*\r?\n<!-- generated by import\b/m);
    return idx === -1 ? content : content.slice(0, idx).trimEnd();
}

const APPENDED_HEADING = /^##[ \t]+(?:Subtasks|Comments)[ \t]*\r?$/gm;

/**
 * Does the tail below a legacy `## Comments` heading look like an imported comment log?
 *
 * The generated shape is `**Author** — YYYY-MM-DD:` / blank / body / blank / `---`,
 * repeated (TaskViewerProvider._buildCommentsSection; LinearSyncService's stub builder
 * emits the same author-line + `---` separator shape). Comment BODIES are free prose, so
 * the "every line matches" test the subtasks checklist uses cannot work here — the
 * discriminator is the frame: the first line after the heading is a bold author line, and
 * at least one `---` separator follows.
 *
 * This matters because `## Comments` blocks were written into ticket documents (shipped
 * 2026-06-22) and the marker never applied to them. Without a shape rule the whole
 * imported comment history is pushed up into the remote DESCRIPTION on the next push —
 * permanent, visible pollution of the operator's ticket, and the opposite of the failure
 * this helper exists to prevent.
 */
function looksLikeImportedCommentLog(meaningful: string[]): boolean {
    if (meaningful.length < 2) { return false; }
    const isAuthorLine = (l: string) => /^\*\*[^*]+\*\*.*$/.test(l.trim());
    return isAuthorLine(meaningful[0]) && meaningful.some(l => /^-{3,}\s*$/.test(l.trim()));
}

/**
 * Cut the appended, import-generated tail from a ticket body before pushing it to the
 * remote — and ONLY that tail.
 *
 * Marker-first: a block carrying `<!-- generated by import` is unambiguous and is always
 * cut (this is what _SUBTASKS_HEADER writes today). Legacy fallback: files written before
 * the marker existed carry a bare `## Subtasks` block, so a heading whose tail runs to EOF
 * and contains nothing but `- [ ]` / `- [x]` checklist lines and their indented `  >`
 * description blocks is treated as generated too — that is exactly the shape
 * _buildSubtaskEntry emits and nothing a human writes by hand. A legacy `## Comments`
 * block gets its own shape rule (see looksLikeImportedCommentLog) because comment bodies
 * are free prose and can never satisfy the checklist test.
 *
 * Everything else stays. A parent ticket whose own description has a `## Subtasks`
 * heading — prose, sub-headings, anything not that exact shape — pushes in full.
 * Returns the body to push plus a flag so the caller can warn instead of losing content
 * silently.
 */
export function stripAppendedBlocksForPush(body: string): { pushBody: string; withheld: boolean } {
    const markerIdx = body.search(/^##[ \t]+(?:Subtasks|Comments)[ \t]*\r?\n<!-- generated by import\b/m);
    if (markerIdx !== -1) {
        return { pushBody: body.slice(0, markerIdx).trimEnd(), withheld: true };
    }

    // Legacy (pre-marker) files. Scan EVERY candidate heading, not just the first: a
    // legacy file can carry a human `## Comments` prose section ABOVE the generated
    // `## Subtasks` checklist, and a first-match-wins probe would land on the prose,
    // conclude "nothing generated here", and push the checklist to the remote.
    APPENDED_HEADING.lastIndex = 0;
    for (let m = APPENDED_HEADING.exec(body); m; m = APPENDED_HEADING.exec(body)) {
        const tail = body.slice(m.index).split(/\r?\n/).slice(1);
        const meaningful = tail.filter(l => l.trim() !== '');
        // `  >` NOT `  > ` — _buildSubtaskEntry renders a blank description line as
        // `  > ` with a trailing space, and any trailing-whitespace strip (editor,
        // formatter, git filter) turns it into `  >`. Requiring the space made a
        // whitespace-normalised legacy file look human-authored and pushed its
        // generated block to the remote.
        const looksGenerated = (meaningful.length > 0
            && meaningful.every(l => /^- \[[ xX]\]/.test(l.trim()) || /^[ \t]{2,}>(?:[ \t].*)?$/.test(l)))
            || (/Comments/.test(m[0]) && looksLikeImportedCommentLog(meaningful));
        if (looksGenerated) {
            return { pushBody: body.slice(0, m.index).trimEnd(), withheld: true };
        }
    }
    return { pushBody: body, withheld: false };
}
