/**
 * The `## Subtasks` block that importTicketSubtasks appends is context for agents
 * reading the local .md — never for the detail pane, which renders its own live
 * Subtasks nav above the description. Cut from the heading carrying the
 * generated-by-import marker to EOF.
 *
 * Keyed on heading + marker, never the heading alone: a ticket whose own
 * description contains "## Subtasks" must render in full.
 *
 * DISPLAY ONLY. `rawContent` (edit + push) must keep the block — pushTicketEdits
 * truncates at the heading so it never reaches the remote, and a save built from
 * stripped content would erase it from the file.
 */
export function stripImportedSubtasksBlock(content: string): string {
    const idx = content.search(/^##[ \t]+Subtasks[ \t]*\r?\n<!-- generated by import\b/m);
    return idx === -1 ? content : content.slice(0, idx).trimEnd();
}
